/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManagementSystem;

import javax.swing.JOptionPane;

/**
 *
 * @author navne
 */
public class AdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomePage
     */
    public AdminHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStudent = new javax.swing.JButton();
        AddResult = new javax.swing.JButton();
        listStudents = new javax.swing.JButton();
        updateStudents = new javax.swing.JButton();
        listStudentResults = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/icons8-student.png"))); // NOI18N
        AddStudent.setText("Add Student");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });
        getContentPane().add(AddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 190, 70));

        AddResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddResult.setText("Add Result");
        AddResult.setMaximumSize(new java.awt.Dimension(184, 71));
        AddResult.setMinimumSize(new java.awt.Dimension(184, 71));
        AddResult.setPreferredSize(new java.awt.Dimension(184, 71));
        AddResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddResultActionPerformed(evt);
            }
        });
        getContentPane().add(AddResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 190, -1));

        listStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listStudents.setText("List Students");
        listStudents.setMaximumSize(new java.awt.Dimension(184, 71));
        listStudents.setMinimumSize(new java.awt.Dimension(184, 71));
        listStudents.setPreferredSize(new java.awt.Dimension(184, 71));
        listStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(listStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 190, -1));

        updateStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateStudents.setText("Update Students");
        updateStudents.setMaximumSize(new java.awt.Dimension(184, 71));
        updateStudents.setMinimumSize(new java.awt.Dimension(184, 71));
        updateStudents.setPreferredSize(new java.awt.Dimension(184, 71));
        updateStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(updateStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 190, -1));

        listStudentResults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listStudentResults.setText("List Student Results");
        listStudentResults.setMaximumSize(new java.awt.Dimension(184, 71));
        listStudentResults.setMinimumSize(new java.awt.Dimension(184, 71));
        listStudentResults.setPreferredSize(new java.awt.Dimension(184, 71));
        listStudentResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentResultsActionPerformed(evt);
            }
        });
        getContentPane().add(listStudentResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 190, -1));

        logOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOut.setText("Logout");
        logOut.setMaximumSize(new java.awt.Dimension(184, 71));
        logOut.setMinimumSize(new java.awt.Dimension(184, 71));
        logOut.setPreferredSize(new java.awt.Dimension(184, 71));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementSystem/schoolPic2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentsActionPerformed
        // TODO add your handling code here:
        UpdateStudent frame = new UpdateStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_updateStudentsActionPerformed

    private void AddResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddResultActionPerformed
        // TODO add your handling code here:
        AddResults frame = new AddResults();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddResultActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        int flag = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit",  "Submit" , JOptionPane.YES_NO_OPTION);
        if(flag == 0){
            setVisible(false);
            Home frame = new Home();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_logOutActionPerformed

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        // TODO add your handling code here:
        AddStudent frame = new AddStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddStudentActionPerformed

    private void listStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentsActionPerformed
        // TODO add your handling code here:
        ListStudents frame = new ListStudents();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_listStudentsActionPerformed

    private void listStudentResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentResultsActionPerformed
        // TODO add your handling code here:
        ListStudentResult frame = new ListStudentResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_listStudentResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddResult;
    private javax.swing.JButton AddStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listStudentResults;
    private javax.swing.JButton listStudents;
    private javax.swing.JButton logOut;
    private javax.swing.JButton updateStudents;
    // End of variables declaration//GEN-END:variables
}
